"""
SPECTER Reporter
Generates HTML, Markdown, and JSON reports from scan findings.
"""

import os
import json
import logging
from datetime import datetime

logger = logging.getLogger("specter.reporter")

SEVERITY_COLORS = {
    "CRITICAL": "#e74c3c",
    "HIGH":     "#e67e22",
    "MEDIUM":   "#f1c40f",
    "LOW":      "#2ecc71",
    "INFO":     "#95a5a6",
}

SEVERITY_BADGE = {
    "CRITICAL": "🔴",
    "HIGH":     "🟠",
    "MEDIUM":   "🟡",
    "LOW":      "🟢",
    "INFO":     "⚪",
}


class Reporter:
    def __init__(self, session: dict, output_dir: str = "reports"):
        self.session    = session
        self.output_dir = output_dir
        self.findings   = session.get("findings", [])
        self.target     = session.get("target", "Unknown")
        self.sid        = session.get("id", "unknown")
        os.makedirs(output_dir, exist_ok=True)

    # ------------------------------------------------------------------
    def generate_all(self) -> dict:
        paths = {}
        paths["html"]     = self._write_html()
        paths["markdown"] = self._write_markdown()
        paths["json"]     = self._write_json()
        return paths

    # ------------------------------------------------------------------
    def _write_json(self) -> str:
        path = os.path.join(self.output_dir, f"{self.sid}_report.json")
        with open(path, "w") as f:
            json.dump(self.session, f, indent=2)
        return path

    # ------------------------------------------------------------------
    def _write_markdown(self) -> str:
        path = os.path.join(self.output_dir, f"{self.sid}_report.md")
        stats = self.session.get("stats", {})
        lines = [
            f"# 👻 SPECTER Security Report",
            f"",
            f"**Target:** `{self.target}`  ",
            f"**Scan Date:** {self.session.get('started', '')[:19]}  ",
            f"**Session ID:** `{self.sid}`  ",
            f"**Status:** {self.session.get('status', '')}  ",
            f"",
            f"---",
            f"",
            f"## Summary",
            f"",
            f"| Severity | Count |",
            f"|----------|-------|",
            f"| 🔴 Critical | {stats.get('critical', 0)} |",
            f"| 🟠 High     | {stats.get('high', 0)} |",
            f"| 🟡 Medium   | {stats.get('medium', 0)} |",
            f"| 🟢 Low      | {stats.get('low', 0)} |",
            f"| ⚪ Info     | {stats.get('info', 0)} |",
            f"| **Total** | **{len(self.findings)}** |",
            f"",
            f"---",
            f"",
            f"## Findings",
            f"",
        ]

        if not self.findings:
            lines.append("*No vulnerabilities confirmed.*")
        else:
            for i, f in enumerate(self.findings, 1):
                badge = SEVERITY_BADGE.get(f.get("severity", "INFO"), "⚪")
                lines += [
                    f"### {i}. {badge} {f.get('title', 'Untitled')}",
                    f"",
                    f"**Severity:** {f.get('severity')}  ",
                    f"**Agent:** {f.get('agent')}  ",
                    f"**Endpoint:** `{f.get('endpoint', '-')}`  ",
                    f"",
                    f"**Description:**  ",
                    f"{f.get('description', '')}",
                    f"",
                ]
                if f.get("poc"):
                    lines += [
                        f"**Proof of Concept:**",
                        f"```",
                        f"{f.get('poc')}",
                        f"```",
                        f"",
                    ]
                if f.get("remediation"):
                    lines += [
                        f"**Remediation:**  ",
                        f"{f.get('remediation')}",
                        f"",
                    ]
                lines.append("---")
                lines.append("")

        lines += [
            f"",
            f"*Generated by SPECTER — github.com/YOUR_USERNAME/SPECTER*",
        ]

        with open(path, "w", encoding="utf-8") as f:
            f.write("\n".join(lines))
        return path

    # ------------------------------------------------------------------
    def _write_html(self) -> str:
        path = os.path.join(self.output_dir, f"{self.sid}_report.html")
        stats = self.session.get("stats", {})

        finding_cards = ""
        for i, f in enumerate(self.findings, 1):
            sev   = f.get("severity", "INFO")
            color = SEVERITY_COLORS.get(sev, "#95a5a6")
            badge = SEVERITY_BADGE.get(sev, "⚪")
            poc_html = f"""
            <div class="poc">
                <strong>Proof of Concept:</strong>
                <pre><code>{f.get('poc', '')}</code></pre>
            </div>""" if f.get("poc") else ""
            rem_html = f"""
            <div class="remediation">
                <strong>🛠 Remediation:</strong> {f.get('remediation', '')}
            </div>""" if f.get("remediation") else ""

            finding_cards += f"""
            <div class="finding" style="border-left: 4px solid {color}">
                <div class="finding-header">
                    <span class="badge" style="background:{color}">{sev}</span>
                    <h3>{i}. {badge} {f.get('title','')}</h3>
                </div>
                <div class="finding-meta">
                    <span>🤖 Agent: {f.get('agent','')}</span>
                    <span>📍 Endpoint: <code>{f.get('endpoint','')}</code></span>
                    <span>🕐 {f.get('timestamp','')[:19]}</span>
                </div>
                <p>{f.get('description','').replace(chr(10), '<br>')}</p>
                {poc_html}
                {rem_html}
            </div>"""

        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>SPECTER Report — {self.target}</title>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ font-family: 'Segoe UI', system-ui, sans-serif; background: #0d1117; color: #c9d1d9; line-height: 1.6; }}
  .container {{ max-width: 1100px; margin: 0 auto; padding: 2rem; }}
  header {{ background: linear-gradient(135deg, #1f1f2e, #2d1b69); padding: 2rem; border-radius: 12px; margin-bottom: 2rem; }}
  header h1 {{ font-size: 2rem; color: #fff; }}
  header h1 span {{ color: #e74c3c; }}
  .meta {{ display: flex; gap: 1.5rem; flex-wrap: wrap; margin-top: 1rem; font-size: 0.9rem; color: #8b949e; }}
  .summary {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(120px, 1fr)); gap: 1rem; margin-bottom: 2rem; }}
  .stat-card {{ background: #161b22; border-radius: 8px; padding: 1rem; text-align: center; border: 1px solid #30363d; }}
  .stat-card .num {{ font-size: 2rem; font-weight: bold; }}
  .stat-card .label {{ font-size: 0.8rem; color: #8b949e; }}
  .finding {{ background: #161b22; border-radius: 8px; padding: 1.5rem; margin-bottom: 1rem; border: 1px solid #30363d; }}
  .finding-header {{ display: flex; align-items: center; gap: 1rem; margin-bottom: 0.75rem; }}
  .finding-header h3 {{ font-size: 1.1rem; color: #e6edf3; }}
  .badge {{ padding: 0.2rem 0.6rem; border-radius: 4px; font-size: 0.75rem; font-weight: bold; color: white; }}
  .finding-meta {{ display: flex; gap: 1.5rem; font-size: 0.8rem; color: #8b949e; margin-bottom: 1rem; flex-wrap: wrap; }}
  .finding-meta code {{ background: #0d1117; padding: 0.1rem 0.3rem; border-radius: 3px; }}
  .poc {{ background: #0d1117; border-radius: 6px; padding: 1rem; margin: 1rem 0; border: 1px solid #30363d; }}
  .poc pre {{ overflow-x: auto; white-space: pre-wrap; font-size: 0.85rem; }}
  .poc code {{ color: #79c0ff; }}
  .remediation {{ background: #0f2a1a; border-radius: 6px; padding: 0.75rem 1rem; margin-top: 0.75rem; border: 1px solid #1a4a2a; color: #56d364; font-size: 0.9rem; }}
  h2 {{ color: #e6edf3; margin-bottom: 1rem; font-size: 1.3rem; }}
  footer {{ text-align: center; color: #484f58; margin-top: 3rem; font-size: 0.85rem; }}
  .no-findings {{ text-align: center; padding: 3rem; color: #56d364; font-size: 1.2rem; }}
</style>
</head>
<body>
<div class="container">
  <header>
    <h1>👻 <span>SPECTER</span> Security Report</h1>
    <div class="meta">
      <span>🎯 Target: <strong>{self.target}</strong></span>
      <span>📅 {self.session.get('started','')[:19]}</span>
      <span>🔖 Session: {self.sid}</span>
      <span>✅ {self.session.get('status','')}</span>
    </div>
  </header>

  <h2>Summary</h2>
  <div class="summary">
    <div class="stat-card"><div class="num" style="color:#e74c3c">{stats.get('critical',0)}</div><div class="label">Critical</div></div>
    <div class="stat-card"><div class="num" style="color:#e67e22">{stats.get('high',0)}</div><div class="label">High</div></div>
    <div class="stat-card"><div class="num" style="color:#f1c40f">{stats.get('medium',0)}</div><div class="label">Medium</div></div>
    <div class="stat-card"><div class="num" style="color:#2ecc71">{stats.get('low',0)}</div><div class="label">Low</div></div>
    <div class="stat-card"><div class="num" style="color:#95a5a6">{stats.get('info',0)}</div><div class="label">Info</div></div>
    <div class="stat-card"><div class="num" style="color:#c9d1d9">{len(self.findings)}</div><div class="label">Total</div></div>
  </div>

  <h2>Findings</h2>
  {"".join([finding_cards]) if self.findings else '<div class="no-findings">✅ No vulnerabilities confirmed in this scan.</div>'}

  <footer>
    Generated by <strong>SPECTER</strong> — github.com/YOUR_USERNAME/SPECTER<br>
    ⚠️ For authorized security testing only.
  </footer>
</div>
</body>
</html>"""

        with open(path, "w", encoding="utf-8") as f:
            f.write(html)
        return path
